In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/sales_data.csv")
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75995,2024-01-30,S005,P0016,Toys,North,233,63,0,29.80,5,Snowy,0,32.23,Winter,0,64
75996,2024-01-30,S005,P0017,Toys,North,137,115,141,42.92,5,Snowy,0,40.73,Winter,0,137
75997,2024-01-30,S005,P0018,Clothing,North,197,44,0,17.81,10,Snowy,0,19.41,Winter,0,68
75998,2024-01-30,S005,P0019,Furniture,North,125,58,0,151.72,0,Snowy,0,143.71,Winter,0,84
75999,2024-01-30,S005,P0020,Toys,North,126,63,59,25.78,10,Snowy,0,29.32,Winter,0,73

In [37]:
clean_df = df.copy()

In [38]:
clean_df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

In [39]:
missing_percentage = (clean_df.isnull().sum() / len(clean_df)) * 100

missing_percentage.sort_values(ascending=False)

Date                  0.0
Store ID              0.0
Product ID            0.0
Category              0.0
Region                0.0
Inventory Level       0.0
Units Sold            0.0
Units Ordered         0.0
Price                 0.0
Discount              0.0
Weather Condition     0.0
Promotion             0.0
Competitor Pricing    0.0
Seasonality           0.0
Epidemic              0.0
Demand                0.0
dtype: float64

In [40]:
numeric_columns = clean_df.select_dtypes(include=np.number).columns

for column in numeric_columns:
    if clean_df[column].isnull().sum() > 0:
        clean_df[column] = clean_df[column].fillna(
            clean_df[column].median()
        )

In [41]:
categorical_columns = clean_df.select_dtypes(include=["object", "string", "category"]).columns

for column in categorical_columns:
    if clean_df[column].isnull().sum() > 0:
        clean_df[column] = clean_df[column].fillna(
            clean_df[column].mode()[0]
        )

In [42]:
clean_df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

In [43]:
clean_df.duplicated().sum()

np.int64(0)

In [44]:
clean_df = clean_df.drop_duplicates()

In [45]:
clean_df["Date"].dtype

In [46]:
clean_df["Date"] = pd.to_datetime(clean_df["Date"],errors="coerce")

In [47]:
clean_df["Date"].isnull().sum()

np.int64(0)

In [48]:
clean_df.describe().T

,count,mean,min,25%,50%,75%,max,std
Date,76000,2023-01-15 12:00:00,2022-01-01 00:00:00,2022-07-09 18:00:00,2023-01-15 12:00:00,2023-07-24 06:00:00,2024-01-30 00:00:00,NaN
Inventory Level,76000.0,301.062842,0.0,136.0,227.0,408.0,2267.0,226.510161
Units Sold,76000.0,88.827316,0.0,58.0,84.0,114.0,426.0,43.994525
Units Ordered,76000.0,89.090645,0.0,0.0,0.0,121.0,1616.0,162.404627
Price,76000.0,67.726028,4.74,31.9975,64.5,95.83,228.03,39.377899
Discount,76000.0,9.087039,0.0,5.0,10.0,10.0,25.0,7.475781
Promotion,76000.0,0.328947,0.0,0.0,0.0,1.0,1.0,0.469834
Competitor Pricing,76000.0,69.454029,4.29,32.62,65.7,97.9325,261.22,40.943818
Epidemic,76000.0,0.2,0.0,0.0,0.0,0.0,1.0,0.400003
Demand,76000.0,104.317158,4.0,71.0,100.0,133.0,430.0,46.964801

In [49]:
numeric_columns = [
    "Inventory Level",
    "Units Sold",
    "Units Ordered",
    "Price",
    "Discount",
    "Competitor Pricing",
    "Demand"
]

for column in numeric_columns:
    print(
        column,
        "negative values:",
        (clean_df[column] < 0).sum()
    )

Inventory Level negative values: 0
Units Sold negative values: 0
Units Ordered negative values: 0
Price negative values: 0
Discount negative values: 0
Competitor Pricing negative values: 0
Demand negative values: 0

In [50]:
for column in numeric_columns:
    print(
        column,
        "zero values:",
        (clean_df[column] == 0).sum()
    )

Inventory Level zero values: 406
Units Sold zero values: 406
Units Ordered zero values: 47107
Price zero values: 0
Discount zero values: 17126
Competitor Pricing zero values: 0
Demand zero values: 0

In [51]:
print(clean_df["Promotion"].value_counts())
print(clean_df["Epidemic"].value_counts())

Promotion
0    51000
1    25000
Name: count, dtype: int64
Epidemic
0    60800
1    15200
Name: count, dtype: int64

In [52]:
clean_df["Discount"].describe()

count    76000.000000
mean         9.087039
std          7.475781
min          0.000000
25%          5.000000
50%         10.000000
75%         10.000000
max         25.000000
Name: Discount, dtype: float64

In [53]:
clean_df[(clean_df["Discount"] < 0) | (clean_df["Discount"] > 100)]

Empty DataFrame
Columns: [Date, Store ID, Product ID, Category, Region, Inventory Level, Units Sold, Units Ordered, Price, Discount, Weather Condition, Promotion, Competitor Pricing, Seasonality, Epidemic, Demand]
Index: []

In [54]:
clean_df[
    clean_df["Competitor Pricing"] <= 0
]

Empty DataFrame
Columns: [Date, Store ID, Product ID, Category, Region, Inventory Level, Units Sold, Units Ordered, Price, Discount, Weather Condition, Promotion, Competitor Pricing, Seasonality, Epidemic, Demand]
Index: []

In [55]:
clean_df[
    clean_df["Price"] <= 0
]

Empty DataFrame
Columns: [Date, Store ID, Product ID, Category, Region, Inventory Level, Units Sold, Units Ordered, Price, Discount, Weather Condition, Promotion, Competitor Pricing, Seasonality, Epidemic, Demand]
Index: []

In [56]:
sales_inventory_issue = clean_df[
    clean_df["Units Sold"] > clean_df["Inventory Level"]
]

print("Units Sold > Inventory Level:", len(sales_inventory_issue))

Units Sold > Inventory Level: 0

In [57]:
clean_df["Units Ordered"].describe()

count    76000.000000
mean        89.090645
std        162.404627
min          0.000000
25%          0.000000
50%          0.000000
75%        121.000000
max       1616.000000
Name: Units Ordered, dtype: float64

In [58]:
clean_df[
    clean_df["Units Ordered"] < 0
]

Empty DataFrame
Columns: [Date, Store ID, Product ID, Category, Region, Inventory Level, Units Sold, Units Ordered, Price, Discount, Weather Condition, Promotion, Competitor Pricing, Seasonality, Epidemic, Demand]
Index: []

In [59]:
clean_df["Demand"].describe()

count    76000.000000
mean       104.317158
std         46.964801
min          4.000000
25%         71.000000
50%        100.000000
75%        133.000000
max        430.000000
Name: Demand, dtype: float64

In [60]:
clean_df[
    clean_df["Demand"] < 0
]

Empty DataFrame
Columns: [Date, Store ID, Product ID, Category, Region, Inventory Level, Units Sold, Units Ordered, Price, Discount, Weather Condition, Promotion, Competitor Pricing, Seasonality, Epidemic, Demand]
Index: []

In [61]:
original_shape = df.shape

In [62]:
cleaned_shape = clean_df.shape

print("Original shape:", original_shape)
print("Cleaned shape:", cleaned_shape)

Original shape: (76000, 16)
Cleaned shape: (76000, 16)

In [63]:
clean_df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

In [64]:
clean_df.duplicated().sum()

np.int64(0)

In [65]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                76000 non-null  datetime64[us]
 1   Store ID            76000 non-null  str
 2   Product ID          76000 non-null  str
 3   Category            76000 non-null  str
 4   Region              76000 non-null  str
 5   Inventory Level     76000 non-null  int64
 6   Units Sold          76000 non-null  int64
 7   Units Ordered       76000 non-null  int64
 8   Price               76000 non-null  float64
 9   Discount            76000 non-null  int64
 10  Weather Condition   76000 non-null  str
 11  Promotion           76000 non-null  int64
 12  Competitor Pricing  76000 non-null  float64
 13  Seasonality         76000 non-null  str
 14  Epidemic            76000 non-null  int64
 15  Demand              76000 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(7), str(6)
memory usage: 11.7 MB

In [66]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [67]:
clean_df.to_csv(
    "../data/processed/cleaned_sales_data.csv",
    index=False
)